lectures/thespoon-with-activerecord/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :restaurants

  # delete 'restaurants/:id', to: 'restaurants#destroy'
  # patch 'restaurants/:id', to: 'restaurants#update', as: 'restaurant'
  # get 'restaurants/:id/edit', to: 'restaurants#edit'
  # post 'restaurants', to: 'restaurants#create'
  # get 'restaurants/new', to: 'restaurants#new', as: 'new_restaurant'
  # get 'restaurants/:id', to: 'restaurants#show'
  # get 'restaurants', to: 'restaurants#index'

end

lectures/thespoon-with-activerecord/app/models/restaurant.rb
class Restaurant < ApplicationRecord
end

lectures/thespoon-with-activerecord/app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    restaurant = Restaurant.new(restaurant_params)
    restaurant.save

    redirect_to restaurants_path
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)

    redirect_to restaurants_path
  end

  def destroy
    @restaurant.destroy

    redirect_to restaurants_path
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :rating, :address)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

end

lectures/thespoon-with-activerecord/app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

lectures/thespoon-with-activerecord/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThespoonWithActiverecord</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

lectures/thespoon-with-activerecord/app/views/restaurants/_form.html.erb
<%= simple_form_for restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :rating %>
  <%= f.submit %>
<% end %>

lectures/thespoon-with-activerecord/app/views/restaurants/edit.html.erb
<%= render "form", restaurant: @restaurant %>

lectures/thespoon-with-activerecord/app/views/restaurants/index.html.erb
<ul>
  <% @restaurants.each do |restaurant| %>
    <li>
      <%= link_to restaurant.name, restaurant_path(restaurant) %>
      <%= link_to "Delete", restaurant_path(restaurant), method: 'DELETE', data: { confirm: "Are you sure?" } %>
    </li>
  <% end %>
</ul>

lectures/thespoon-with-activerecord/app/views/restaurants/new.html.erb
<%= render "form", restaurant: @restaurant %>

lectures/thespoon-with-activerecord/app/views/restaurants/show.html.erb
<h2><%= @restaurant.name %></h2>
<p>Rating: <%= @restaurant.rating %></p>
<p><%= @restaurant.address %></p>