livecode/airbnb-static/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/', to: 'flats#index', as: 'flats'
  get '/flats/:id', to: 'flats#show', as: 'flat'

  # localhost:3000/flats/14      -> params[:id] = 14
  # localhost:3000/flats/985     -> params[:id] = 985
  # localhost:3000/flats/bananas -> params[:id] = bananas
  # localhost:3000/flats/666     -> params[:id] = 666


end

livecode/airbnb-static/app/controllers/flats_controller.rb
require "open-uri"

class FlatsController < ApplicationController

  URL = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"

  before_action :set_flats

  def index
  end

  def show
    @flat = @flats.find { |flat_hash| flat_hash['id'] == params[:id].to_i }
  end

  private
  def set_flats
    @flats = JSON.parse(open(URL).read)
  end

end

livecode/airbnb-static/app/helpers/flats_helper.rb
module FlatsHelper
end

livecode/airbnb-static/app/views/flats/index.html.erb
<h1>Flats</h1>

<ol>
  <% @flats.each do |flat| %>
    <li>
      <%= link_to "#{flat['name']} at #{flat['priceCurrency']} #{flat['price']}", flat_path(flat['id']) %>
    </li>
  <% end %>
</ol>

livecode/airbnb-static/app/views/flats/show.html.erb
<%= link_to "Go back to all flats", flats_path %>

<h1>Flat of ID <%= @flat['id'] %></h1>
<h2><%= @flat['name'] %></h2>
<h3>Price: <%= "#{@flat['priceCurrency']} #{@flat['price']}" %></h3>
<img src="<%= @flat['imageUrl'] %>" alt="" width=800 height=800>

livecode/airbnb-static/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbStatic</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>