livecode/lost_pets/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'pets', to: 'pets#index', as: 'pets'
  post 'pets', to: 'pets#create'

  get 'pets/new', to: 'pets#new', as: 'new_pet'
  get 'pets/:id', to: 'pets#show', as: 'pet'
  delete 'pets/:id', to: 'pets#destroy'
  patch 'pets/:id', to: 'pets#update'

  get 'pets/:id/edit', to: 'pets#edit', as: 'edit_pet'

end

livecode/lost_pets/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

livecode/lost_pets/app/models/pet.rb
class Pet < ApplicationRecord

  SPECIES = ["dog", "cat", "bird", "turtle", "hamster", "rabbit"]

  validates :name, presence: true
  validates :rescued_at, presence: true
  validates :species, inclusion: { in: SPECIES }

end

livecode/lost_pets/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

livecode/lost_pets/app/controllers/pets_controller.rb
class PetsController < ApplicationController

  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  def index
    @pets = Pet.all
  end

  def show
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.save

    redirect_to pets_path
  end

  def edit
  end

  def update
    @pet.update(pet_params)

    redirect_to pets_path
  end

  def destroy
    @pet.destroy

    redirect_to pets_path
  end

  private
  def pet_params
    params.require(:pet).permit(:name, :species, :gender, :rescued_at)
  end

  def set_pet
    @pet = Pet.find(params[:id])
  end

end

livecode/lost_pets/app/helpers/application_helper.rb
module ApplicationHelper
end

livecode/lost_pets/app/helpers/pets_helper.rb
module PetsHelper
end

livecode/lost_pets/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

livecode/lost_pets/app/views/pets/_form.html.erb
<!-- partial -->

<%= simple_form_for pet do |f| %>
  <%= f.input :name %>
  <%= f.input :species, collection: Pet::SPECIES %>
  <%= f.input :gender %>
  <%= f.input :rescued_at %>

  <%= f.submit submit_msg, class: 'btn btn-primary' %>
<% end %>

livecode/lost_pets/app/views/pets/edit.html.erb
<%= render 'form', pet: @pet, submit_msg: 'Update' %>

livecode/lost_pets/app/views/pets/index.html.erb
<!-- name + species -->

<h1>Pets summary</h1>

<ul>
  <% @pets.each do |pet| %>
    <li>
      <p><%= link_to "#{pet.name} #{pet.species}", pet_path(pet) %></p>
    </li>
  <% end %>
</ul>

<%= link_to "Rescued a pet?", new_pet_path, class: 'btn btn-secondary' %>

livecode/lost_pets/app/views/pets/new.html.erb
<%= render 'form', pet: @pet, submit_msg: 'Create' %>

livecode/lost_pets/app/views/pets/show.html.erb
<%= link_to "Back to main page", pets_path, class: 'btn btn-primary' %>

<h1><%= @pet.name %></h1>
<h2><%= @pet.species %></h2>
<h3><%= @pet.rescued_at %></h3>
<h3><%= @pet.gender %></h3>

<%= link_to "Adopted!", pet_path(@pet), method: 'DELETE', data: { confirm: "Are you sure it was 'adopted'?" }, class: 'btn btn-danger' %>

<%= link_to "Edit #{@pet.name}", edit_pet_path(@pet), class: 'btn btn-warning' %>